config/routes.rb
Spree::Core::Engine.routes.draw do
  
  namespace :admin do
    resources :banner_boxes do
      collection do
        post :update_positions
      end
      member do
        get :clone
      end
    end
    resource :banner_box_settings
  end
end

app/models/spree/banner_box.rb
module Spree
  class BannerBox < ActiveRecord::Base
    acts_as_list :scope => :category
    
    has_attached_file :attachment,
                :url  => "/spree/banners/:id/:style_:basename.:extension",
                :path => ":rails_root/public/spree/banners/:id/:style_:basename.:extension",
                :styles => { :mini => "80x80#", :small => "120x120#" },
                :convert_options => { :all => '-strip -auto-orient' }
    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions

    validates_presence_of :category
    validates_attachment_presence :attachment
    validates_attachment_content_type :attachment, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/jpg', 'image/x-png', 'image/pjpeg'], :message => I18n.t(:images_only)

    scope :enabled, lambda { |*categories|
      if categories.empty?
        where(:enabled => true)
      else
        where(:enabled => true).where(:category => categories)
      end
    }

    # Load user defined paperclip settings
    include Spree::Core::S3Support
    supports_s3 :attachment
    
    Spree::BannerBox.attachment_definitions[:attachment][:styles] = ActiveSupport::JSON.decode(Spree::Config[:banner_styles])
    Spree::BannerBox.attachment_definitions[:attachment][:path] = Spree::Config[:banner_path]
    Spree::BannerBox.attachment_definitions[:attachment][:url] = Spree::Config[:banner_url]
    Spree::BannerBox.attachment_definitions[:attachment][:default_url] = Spree::Config[:banner_default_url]
    Spree::BannerBox.attachment_definitions[:attachment][:default_style] = Spree::Config[:banner_default_style]
    
    # for adding banner_boxes which are closely related to existing ones
    # define "duplicate_extra" for site-specific actions, eg for additional fields
    def duplicate
      enhance_settings
      p = self.dup
      p.category = 'COPY OF ' + category
      p.created_at = p.updated_at = nil
      p.url = url
      p.attachment = attachment

      # allow site to do some customization
      p.send(:duplicate_extra, self) if p.respond_to?(:duplicate_extra)
      p.save!
      p
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width = geometry.width
      self.attachment_height = geometry.height
    end

    def enhance_settings
      extended_hash = {}
      ActiveSupport::JSON.decode(SpreeBanner::Config[:banner_styles]).each do |key,value|
        extended_hash[:"#{key}"] = value
      end
      Spree::BannerBox.attachment_definitions[:attachment][:styles] = extended_hash
      Spree::BannerBox.attachment_definitions[:attachment][:path] = SpreeBanner::Config[:banner_path]
      Spree::BannerBox.attachment_definitions[:attachment][:url] = SpreeBanner::Config[:banner_url]
      Spree::BannerBox.attachment_definitions[:attachment][:default_url] = SpreeBanner::Config[:banner_default_url]
      Spree::BannerBox.attachment_definitions[:attachment][:default_style] = SpreeBanner::Config[:banner_default_style]
    end

    def self.categories_for_select
      unscoped.pluck(:category).uniq.sort
    end

  end
end

app/controllers/spree/admin/banner_boxes_controller.rb
module Spree
  module Admin
    class BannerBoxesController < ResourceController
      
      def index
        respond_with(@collection)
      end
      
      def show
        redirect_to( :action => :edit )
      end
      
      def update
        @banner_box.enhance_settings
        super
      end

      def clone
        @new = @banner_box.duplicate

        if @new.save
          flash.notice = I18n.t('notice_messages.banner_box_cloned')
        else
          flash.notice = I18n.t('notice_messages.banner_box_not_cloned')
        end

        respond_with(@new) { |format| format.html { redirect_to edit_admin_banner_box_url(@new) } }
      end
      
      protected
      def find_resource
        Spree::BannerBox.find(params[:id])
      end
      
      def location_after_save
         edit_admin_banner_box_url(@banner_box)
      end
      
      def collection
        return @collection if @collection.present?
        params[:q] ||= {}
        params[:q][:s] ||= "category, position asc"
        
        @search = super.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(Spree::Config[:admin_products_per_page])
      end
    end
  end
end

app/helpers/spree/banner_boxes_helper.rb
module Spree
  module BannerBoxesHelper

    def insert_banner_box(params={})
      params[:category] ||= "home"
      params[:class] ||= "banner"
      params[:style] ||= SpreeBanner::Config[:banner_default_style]
      params[:list] ||= false
      banners = Spree::BannerBox.enabled(params[:category]).order(:position)
      return '' if banners.empty?

      if params[:list]
        content_tag :ul do
          banners.map do |ban|
            content_tag :li, :class => params[:class] do
              link_to (ban.url.blank? ? "javascript: void(0)" : ban.url) do
                src = ban.attachment.url(params[:style].to_sym)
                image_tag(src, :alt => ban.alt_text.presence || image_alt(src))
              end
            end
          end.join.html_safe
        end
      else
        banners.map do |ban|
          content_tag :div, :class => params[:class] do
            link_to (ban.url.blank? ? "javascript: void(0)" : ban.url) do
              src = ban.attachment.url(params[:style].to_sym)
              image_tag(ban.attachment.url(params[:style].to_sym), :alt => ban.alt_text.presence || image_alt(src))
            end
          end
        end.join.html_safe
      end
    end

  end
end

app/views/spree/admin/banner_boxes/_form.html.erb
<div data-hook="admin_banner_box_form_fields" class="row">

  <div class="left eight columns alpha" data-hook="admin_banner_box_form_left">
    <%= f.field_container :category do %>
      <%= f.label :category, raw(t(:category) + content_tag(:span, ' *', :class => 'required')) %>
      <%= f.text_field :category, :class => 'fullwidth title' %>
      <%= f.error_message_on :category %>
    <% end %>

    <%= f.field_container :url do %>
      <%= f.label :url, raw(t(:url)) %>
      <%= f.text_field :url, :class => 'fullwidth title' %>
      <%= f.error_message_on :url %>
    <% end %>
  </div>

  <div class="right eight columns omega" data-hook="admin_banner_box_form_right">
    <% unless f.object.new_record? %>
      <div data-hook="thumbnail" class="field alpha two columns">
        <%= f.label t(:thumbnail) %><br>
        <%= link_to image_tag(@banner_box.attachment.url(:mini)), @banner_box.attachment.url(:small) %>
      </div>
    <% end %>

    <%= f.field_container :attachment do %>
      <%= f.label :attachment, t(:attachment) %><br />
      <%= f.file_field :attachment %>
      <%= f.error_message_on :attachment %>
    <% end %>
    <div class="clear"></div>

    <%= f.field_container :alt_text do %>
      <%= f.label :alt_text, t(:alt_text) %>
      <%= f.text_field :alt_text, :class => 'fullwidth' %>
      <%= f.error_message_on :alt_text %>
    <% end %>

    <%= f.field_container :enabled do %>
      <%= f.label :enabled, t(:enabled) %><br />
      <%= f.check_box :enabled %>
      <%= f.error_message_on :enabled %>
    <% end %>
  </div>

  <div class="clear"></div>

  <div data-hook="admin_banner_box_form_additional_fields"></div>

  <div class="clear"></div>
</div>

app/views/spree/admin/banner_boxes/edit.html.erb
<%= render :partial => 'spree/admin/shared/banner_box_sub_menu' %>

<% content_for :page_actions do %>
  <li><%= button_link_to t(:back_to_banner_boxes_list), admin_banner_boxes_url, :icon => 'icon-arrow-left' %></li>
  <li id="new_banner_box_link">
    <%= button_link_to t(:new_banner_box), new_object_url, { :icon => 'icon-plus', :id => 'admin_new_banner_box' } %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @banner_box } %>

<%= form_for [:admin, @banner_box], :method => :put, :html => { :multipart => true } do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/banner_boxes/index.html.erb
<% content_for :page_title do %>
  <%= t(:listing_banner_boxes) %>
<% end %>

<% content_for :page_actions do %>
  <div class="toolbar" data-hook="toolbar">
    <ul class="actions header-action-links inline-menu">
      <li id="new_banner_box_link">
        <%= button_link_to t(:new_banner_box), new_object_url, { :remote => true, :icon => 'icon-plus', :id => 'admin_new_banner_box' } %>
      </li>
    </ul>
  </div>
<% end %>

<%= render :partial => 'spree/admin/shared/banner_box_sub_menu' %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_banner_sidebar">

    <%= search_form_for [:admin, @search] do |f| %>
        <%- locals = {:f => f} %>
        <div data-hook="admin_banner_index_search">
          <div class="alpha four columns">
            <div class="field">
              <%= f.label :category_eq, Spree.t(:category) %>
              <%= f.select :category_eq, Spree::BannerBox.categories_for_select, {:include_blank => true}, {:class => 'select2 fullwidth'} %>
            </div>
          </div>
          <div class="eight columns">
            <div class="field">
              <%= f.label :url_cont, Spree.t(:url) %>
              <%= f.text_field :url_cont, :size => 15 %>
            </div>
          </div>
          <div class="three columns omega">
            <div class="field checkbox">
              <label>
                <%= f.check_box :enabled_true %>
                <%= Spree.t(:show_only_enabled) %>
              </label>
            </div>
        </div>

        <div class="clear"></div>

        <div class="form-buttons actions filter-actions" data-hook="admin_banner_index_search_buttons">
          <%= button Spree.t(:search), 'icon-search' %>
        </div>
    <% end %>
  </div>
<% end %>


<div id="new_banner_box" data-hook></div>

<% if @collection.any? %>
<table class="index sortable" id="listing_banner_boxes" data-sortable-link="<%= update_positions_admin_banner_boxes_url() %>">
  <colgroup>
  <col style="width: 5%">
  <col style="width: 15%;">
  <col style="width: 10%;">
  <col style="width: 10%;">
  <col style="width: 17%;">
</colgroup>
<thead>
  <tr data-hook="admin_banner_index_headers">
    <th colspan="2"><%= t(:thumbnail) %></th>
    <th><%= t(:category) %></th>
    <th><%= t(:url) %></th>
    <th data-hook="admin_banner_index_header_actions" class="actions"></th>
  </tr>
</thead>
<tbody>
  <% @collection.each do |banner_box| %>
  <tr id="<%= spree_dom_id banner_box %>" data-hook="admin_banner_boxes_index_rows" class="<%= cycle('odd', 'even') %>">
    <td class="no-border">
      <span class="handle"></span>
    </td>
    <td class="align-center"><%= image_tag(banner_box.attachment(:mini)) %></td>
    <td class="align-center"><%= banner_box.category rescue '' %></td>
    <td class="align-center"><%= banner_box.url rescue '' %></td>
    <td class="actions" data-hook="admin_banner_index_row_actions">
      <%= link_to_edit banner_box, :no_text => true, :class => 'edit' %>
      &nbsp;
      <%= link_to_with_icon 'icon-copy', t(:clone), clone_admin_banner_box_url(banner_box), :no_text => true, :class => 'clone' %>
            &nbsp;
      <%= link_to_delete banner_box, :no_text => true %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>
<% else %>
<div class="no-objects-found">
  <%= t(:no_results) %>
</div>
<% end %>

<%= paginate @collection %>

app/views/spree/admin/banner_boxes/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @banner_box } %>

<%= form_for [:admin, @banner_box], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_banner_box">
    <legend align="center"><%= t(:new_banner_box) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/banner_boxes/new.js.erb
$("#new_banner_box").html('<%= escape_javascript(render :template => "spree/admin/banner_boxes/new", :formats => [:html], :handlers => [:erb]) %>');
$("#admin_new_banner_box").parent().hide();