config/routes.rb
Spree::Core::Engine.routes.draw do
  
  namespace :admin do
    resources :banner_boxes do
      collection do
        post :update_positions
      end
      member do
        get :clone
      end
    end
    resource :banner_box_settings
  end
end

app/controllers/spree/admin/banner_settings_controller.rb
module Spree
  module Admin
    class BannerSettingsController < Spree::Admin::BaseController
      def show
        styles = ActiveSupport::JSON.decode(Spree::Config[:banner_styles])
        @styles_list = styles.collect { |k, v| k }.join(", ")
      end

      def edit
        @styles = ActiveSupport::JSON.decode(Spree::Config[:banner_styles])
      end

      def update
        update_styles(params)

        Spree::Config.set(params[:preferences])
        update_paperclip_settings

        respond_to do |format|
          format.html {
            flash[:notice] = t(:banner_settings_updated)
            redirect_to admin_banner_settings_path
          }
        end
      end


      private

      def update_styles(params)
        params[:new_banner_styles].each do |index, style|
          params[:banner_styles][style[:name]] = style[:value] unless style[:value].empty?
        end if params[:new_banner_styles].present?

        styles = params[:banner_styles]

        Spree::Config[:banner_styles] = ActiveSupport::JSON.encode(styles) unless styles.nil?
      end

      def update_paperclip_settings
        Spree::Banner.attachment_definitions[:attachment][:styles] = ActiveSupport::JSON.decode(Spree::Config[:banner_styles])
        Spree::Banner.attachment_definitions[:attachment][:path] = Spree::Config[:banner_path]
        Spree::Banner.attachment_definitions[:attachment][:default_url] = Spree::Config[:banner_default_url]
        Spree::Banner.attachment_definitions[:attachment][:default_style] = Spree::Config[:banner_default_style]
      end
    end
  end
end

app/views/spree/admin/banner_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t(:banner_settings) %></h1>

<p><span class="warning"><%= t(:banner_settings_warning) %></span></p>

<%= form_tag admin_banner_settings_path, :method => :put do %>

  <p data-hook="banner_path">
    <label>
      <%= label_tag 'preferences[banner_path]', t(:banner_path) %>
      <%= preference_field_tag 'preferences[banner_path]', Spree::Config[:banner_path], :type => :string %>
    </label>
  </p>

  <p data-hook="banner_default_url">
    <label>
      <%= label_tag 'preferences[banner_default_url]', t(:banner_default_url) %>
      <%= preference_field_tag 'preferences[banner_default_url]', Spree::Config[:banner_default_url], :type => :string %>
    </label>
  </p>

  <p data-hook="banner_default_style">
    <label>
      <%= label_tag 'preferences[banner_default_style]', t(:banner_default_style) %>
      <%= collection_select 'preferences', 'banner_default_style', @styles, :first, :first, {:selected => Spree::Config[:banner_default_style] } %> 
    </label>
  </p>

  <div id="banner_styles" data-hook="banner_styles">
    <h2><%= t(:banner_styles) %></h2>
    <ul id="styles_list">
      <% @styles.each do |style_name, style_value| %>
        <li>
          <%= label_tag "banner_styles[#{style_name}]", style_name %>
          <%= text_field_tag "banner_styles[#{style_name}]", style_value %>
          <a href="#" alt="Destroy" class="destroy_banner_style">x</a>
        </li>
      <% end %>
    </ul>
    <p><a href="#" alt="Add Style" class="add_banner_style"><%= t(:add_new_style) %></a></p>
  </div>

  <p class="form-buttons" data-hook="buttons">
    <%= button t(:update) %>
  </p>

<% end %>

app/views/spree/admin/banner_settings/show.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t(:banner_settings) %></h1>

<h4><%= t(:banner_path) %>: <%= Spree::Config[:banner_path] %></h4>
<h4><%= t(:banner_default_url) %>: <%= Spree::Config[:banner_default_url] %></h4>
<h4><%= t(:banner_default_style) %>: <%= Spree::Config[:banner_default_style] %></h4>
<h4><%= t(:defined_paperclip_styles) %>: <%= @styles_list %></h4>

<%= link_to_with_icon 'edit', t(:edit), edit_admin_banner_settings_path, :id => 'admin_banner_settings_link' %>